"""
Generate Magma input for the Chabauty-Coleman scan described in
Section 3 of Peschmann (2026).

For each coprime pair (m, n) with m > n > 0 and m - n odd, the
genus-2 curve C_{m,n}: y^2 = Q(x) * R(x) has the palindromic factors

    Q(x) = W2 * x^2 - 2*V2 * x + W2
    R(x) = (m*n)^2 * x^4 + (m^4 - 4*m^2*n^2 + n^4) * x^2 + (m*n)^2

with V2 = 2*m*n, W2 = m^2 + n^2.

A rational point on C_{m,n} corresponds to a perfect Euler brick
with second Euclid pair (m, n). The Magma script emitted by this
module applies Chabauty0 to the Jacobian of this curve.

Usage:
    python generate_chabauty_curves.py [max_m] [output.magma]
"""

from __future__ import annotations

import sys
from math import gcd
from pathlib import Path


def genus2_polynomial(m: int, n: int) -> list[int]:
    """Return the integer coefficients of Q(x) * R(x) in descending
    degree order, [c6, c5, c4, c3, c2, c1, c0].
    """
    mn = m * n
    v2 = 2 * mn
    w2 = m * m + n * n
    mn2 = mn * mn
    middle = m ** 4 - 4 * m * m * n * n + n ** 4

    q = [w2, -2 * v2, w2]
    r = [mn2, 0, middle, 0, mn2]

    prod = [0] * 7
    for i, qi in enumerate(q):
        for j, rj in enumerate(r):
            prod[i + j] += qi * rj
    return prod


def polynomial_to_magma(coeffs: list[int], var: str = "x") -> str:
    """Render a coefficient list as a Magma polynomial expression."""
    terms = []
    degree = len(coeffs) - 1
    for k, c in enumerate(coeffs):
        exp = degree - k
        if c == 0:
            continue
        if exp == 0:
            terms.append(f"{c}")
        elif exp == 1:
            terms.append(f"{c}*{var}")
        else:
            terms.append(f"{c}*{var}^{exp}")
    return " + ".join(terms).replace("+ -", "- ")


def chabauty_magma_line(m: int, n: int) -> str:
    """Return a single Magma statement applying Chabauty0 to C_{m,n}."""
    coeffs = genus2_polynomial(m, n)
    poly = polynomial_to_magma(coeffs)
    return (
        f"try f := {poly}; "
        f"C := HyperellipticCurve(f); "
        f"pts := Chabauty0(Jacobian(C)); "
        f'printf "m={m},n={n}: %o\\n", pts; '
        f'catch e printf "m={m},n={n}: ERROR %o\\n", e`Object; '
        f"end try;"
    )


def iterate_euclid_pairs(max_m: int):
    """Yield all coprime (m, n) with m > n > 0, m - n odd, m <= max_m."""
    for m in range(2, max_m + 1):
        for n in range(1, m):
            if gcd(m, n) == 1 and (m - n) % 2 == 1:
                yield (m, n)


def write_magma_script(pairs, out_path: Path, bound_label: str = ""):
    """Write a Magma script that runs Chabauty0 on the genus-2 curve
    for each (m, n) in the given iterable.
    """
    count = 0
    with out_path.open("w") as fh:
        fh.write("// Chabauty-Coleman scan for the perfect cuboid problem\n")
        fh.write("// Generated by generate_chabauty_curves.py\n")
        if bound_label:
            fh.write(f"// Scope: {bound_label}\n")
        fh.write("\n")
        fh.write("R<x> := PolynomialRing(Rationals());\n\n")
        for m, n in pairs:
            fh.write(chabauty_magma_line(m, n))
            fh.write("\n")
            count += 1
    return count


def main() -> int:
    max_m = int(sys.argv[1]) if len(sys.argv) > 1 else 50
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(
        f"chabauty_scan_m_le_{max_m}.magma"
    )

    pairs = list(iterate_euclid_pairs(max_m))
    written = write_magma_script(pairs, out_path,
                                 bound_label=f"m <= {max_m}")

    print(f"Wrote {written} Chabauty0 calls to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
