"""
Generate Magma input for the Himane Theorem 1 curves described in
Section 5 of Peschmann (2026).

For a primitive Pythagorean triple (u1, v1, w1), parametrise the
second triple by t and form

    face(t)  = u1^2 * (t^2 - 1)^2 + 4 * v1^2 * t^2
    space(t) = u1^2 * (t^2 - 1)^2 + 4 * w1^2 * t^2

A perfect Euler brick in this family requires both expressions to be
rational squares. Their product defines a genus-3 curve in t. After
the substitution mu = t^2 (motivated by the palindromic symmetry),
this reduces to a palindromic degree-4 polynomial in mu, which
defines a genus-1 curve (elliptic curve in quartic form).

This module emits Magma code that computes the rank, torsion, and
rational points of that elliptic curve for each selected triple.

Usage:
    python generate_himane_curves.py [max_generator] [output.magma]
"""

from __future__ import annotations

import sys
from math import gcd
from pathlib import Path


def himane_quartic_mu(u1: int, v1: int, w1: int) -> list[int]:
    """Return coefficients of
        face(mu) * space(mu)  in mu,
    where face(mu) = u1^2 * (mu - 1)^2 + 4 * v1^2 * mu
      and space(mu) = u1^2 * (mu - 1)^2 + 4 * w1^2 * mu.
    Output order: [c4, c3, c2, c1, c0].
    """
    # face(mu) = u1^2 * mu^2 + (4*v1^2 - 2*u1^2) * mu + u1^2
    # space(mu) = u1^2 * mu^2 + (4*w1^2 - 2*u1^2) * mu + u1^2
    u1sq = u1 * u1
    face = [u1sq, 4 * v1 * v1 - 2 * u1sq, u1sq]
    space = [u1sq, 4 * w1 * w1 - 2 * u1sq, u1sq]

    prod = [0] * 5
    for i, fi in enumerate(face):
        for j, sj in enumerate(space):
            prod[i + j] += fi * sj
    return prod


def polynomial_to_magma(coeffs: list[int], var: str = "x") -> str:
    terms = []
    degree = len(coeffs) - 1
    for k, c in enumerate(coeffs):
        exp = degree - k
        if c == 0:
            continue
        if exp == 0:
            terms.append(f"{c}")
        elif exp == 1:
            terms.append(f"{c}*{var}")
        else:
            terms.append(f"{c}*{var}^{exp}")
    return " + ".join(terms).replace("+ -", "- ")


def iterate_primitive_triples(max_generator: int):
    """Yield (g, h, u, v, w) for primitive Pythagorean triples with
    generators g > h > 0, coprime, opposite parity, g <= max_generator.
    """
    for g in range(2, max_generator + 1):
        for h in range(1, g):
            if gcd(g, h) != 1 or (g - h) % 2 == 0:
                continue
            u = g * g - h * h
            v = 2 * g * h
            w = g * g + h * h
            yield (g, h, u, v, w)


def himane_magma_block(u1: int, v1: int, w1: int,
                       search_bound: int = 10000) -> str:
    """Magma statements: rank, torsion, and rational-point search."""
    coeffs = himane_quartic_mu(u1, v1, w1)
    poly = polynomial_to_magma(coeffs)
    return (
        f'printf "\\n=== (u1,v1,w1) = ({u1},{v1},{w1}) ===\\n";\n'
        f"f := {poly};\n"
        f"C := HyperellipticCurve(f);\n"
        f"E := EllipticCurve(C);\n"
        f"rk := Rank(E);\n"
        f'printf "  rank: %o\\n", rk;\n'
        f'printf "  torsion: %o\\n", AbelianInvariants(TorsionSubgroup(E));\n'
        f"if rk gt 0 then\n"
        f"  pts := RationalPoints(C : Bound := {search_bound});\n"
        f'  printf "  points: %o\\n", pts;\n'
        f"  for pt in pts do\n"
        f"    if pt[3] ne 0 then\n"
        f'      printf "  mu=%o  is_square=%o\\n", pt[1], IsSquare(pt[1]);\n'
        f"    end if;\n"
        f"  end for;\n"
        f"else\n"
        f'  printf "  rank 0 -> no perfect cuboid for this triple\\n";\n'
        f"end if;\n"
    )


def write_magma_script(triples, out_path: Path, search_bound: int = 10000):
    """Write a Magma script analysing the Himane Theorem 1 quartic for
    each primitive Pythagorean triple in `triples`.
    """
    count = 0
    with out_path.open("w") as fh:
        fh.write("// Himane Theorem 1 elliptic quotient analysis\n")
        fh.write("// Generated by generate_himane_curves.py\n\n")
        fh.write("R<x> := PolynomialRing(Rationals());\n\n")
        for g, h, u1, v1, w1 in triples:
            fh.write(f"// Pythagorean triple ({u1},{v1},{w1}) ")
            fh.write(f"from generators (g,h) = ({g},{h})\n")
            fh.write(himane_magma_block(u1, v1, w1, search_bound))
            fh.write("\n")
            count += 1
    return count


def main() -> int:
    max_generator = int(sys.argv[1]) if len(sys.argv) > 1 else 8
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(
        f"himane_analysis_g_le_{max_generator}.magma"
    )

    triples = list(iterate_primitive_triples(max_generator))
    written = write_magma_script(triples, out_path)

    print(f"Wrote {written} Himane elliptic-curve analyses to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
